load('/Users/weijia/Research/FDA/Code/Simulations/Output/20241118/5.RDA')
list_cover_norm <- lapply(results, function(x){mean(x$coef$cover_coef_norm)})
summary(unlist(list_cover_norm))
list_cover_cox <- lapply(results, function(x){mean(x$coef$cover_coef_cox)})
summary(unlist(list_cover_cox))
list_cover_cma_norm <- lapply(results, function(x){mean(x$coef$cover_cma_coef_norm)})
summary(unlist(list_cover_cma_norm))
list_cover_cma_cox <- lapply(results, function(x){mean(x$coef$cover_cma_coef_cox)})
summary(unlist(list_cover_cma_cox))