---
title: "Simulation Results"
author: "Weijia Qian"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, repr.plot.width = 12, repr.plot.height = 8)
library(CCMHr)
library(gt)
library(kableExtra)
library(MASS)
library(mgcv)
library(patchwork)
library(refund)
library(scam)
library(splines)
library(tidyverse)

theme_set(theme_minimal() + 
            theme(legend.position = "bottom",
                  # axis.text = element_text(size = 15),
                  # axis.title = element_text(size = 15),
                  # legend.title = element_text(size = 15),
                  # legend.text = element_text(size = 15)
                  ))
# theme(axis.text = element_text(size = 15),
#         axis.title = element_text(size = 15),
#         axis.text.x = element_blank(),
#         axis.ticks.x = element_blank(),
#         legend.position = "bottom",
#         legend.box.margin = margin(t = -20, b = 0),
#         legend.title = element_text(size = 15),
#         legend.text = element_text(size = 15))

# Define a custom color palette for the methods
my_colors <- c(
  "FTTM" = "#440154",
  # "mgcv LFCM" = "#414487",
  "LFCM" = "#2A788E",
  "loglogistic lfAFT" = "#7AD151",
  "lognormal lfAFT" = "#FDE725"
)
fig_dir <- "/Users/weijia/Research/FDA/Drafts"

# folder_path <- "/Users/weijia/Research/FDA/Simulations/Output/20250720"
folder_path <- "/Users/weijia/Research/FDA/Simulations/Output/20250819"
rda_files <- list.files(path = folder_path, pattern = "\\.RDA$", full.names = TRUE)
all_results <- list()
for (i in 1:length(rda_files)) {
  all_results[[i]] <- loadRDa(rda_files[[i]])
}
```

### Average Out-of-Sample Brier Score
```{r}
all_info <- data.frame()
# Loop through all scenarios and iterations to extract 'info'
for (scenario in all_results) {
  # print(scenario[[1]]$info$scenario)
  for (iteration in scenario) {
    all_info <- rbind(all_info, iteration$info)
  }
}

# box plot
table_Brier <- all_info %>%
  pivot_longer(cols = c("Brier_norm", "Brier_cox", "Brier_faft2"),
               names_to = "type",
               values_to = "value") %>%
  mutate(est_model = case_when(
            str_detect(type, "cox") ~ "LFCM",
            str_detect(type, "fttm") ~ "FTTM",
            str_detect(type, "norm") ~ "lognormal lfAFT",
            str_detect(type, "faft2") ~ "loglogistic lfAFT",
            .default = "lognormal lfAFT"),
         est_model = factor(est_model, 
                            levels = c("loglogistic lfAFT", "lognormal lfAFT", "LFCM", "FTTM")),
         family = recode(family, "cox.ph" = "CoxPH"),
         log_value = log(value))

plot_Brier <- table_Brier %>%
  filter(beta_type == "simple") %>%
  ggplot(aes(factor(nS), value, fill = est_model)) + 
  geom_boxplot(outliers = FALSE, fatten = 1.3) +
  scale_fill_manual(values = my_colors) +
  facet_grid(family~n, labeller = labeller(n = label_both, family = label_value), scales = "free") +
  labs(x = "Density of grid (p)", y = "Out-of-sample Brier score", fill = "Model"
       )

ggsave(file.path(fig_dir, "fig3.jpeg"), plot_Brier, width = 6, height = 4, dpi = 500)

```

### MISE for Estimated Coefficient Functions Across Iterations
```{r}
all_coef <- data.frame() 

# Loop through all scenarios and iterations to extract 'coef'
for (scenario in all_results) {
  for (iteration in scenario) {
    
    # Extract data for the current iteration
    tmp_data <- data.frame(scenario = iteration$info$scenario,
                           iter = iteration$info$iter,
                           family = iteration$info$family,
                           n = iteration$info$n,
                           nS = iteration$info$nS,
                           b = iteration$info$b,
                           #time = time,
                           beta_type = iteration$info$beta_type,
                           mise_coef_norm = mean(iteration$coef$se_coef_norm),
                           mise_coef_cox = mean(iteration$coef$se_coef_cox),
                           mise_coef_faft = mean(iteration$coef$se_coef_faft),
                           mise_coef_faft2 = mean(iteration$coef$se_coef_faft2),
                           cp_coef_norm = mean(iteration$coef$cover_coef_norm),
                           cp_coef_cox = mean(iteration$coef$cover_coef_cox),
                           cp_coef_faft = mean(iteration$coef$cover_coef_faft),
                           cp_coef_faft2 = mean(iteration$coef$cover_coef_faft2),
                           cp_cma_coef_norm = all(iteration$coef$cover_cma_coef_norm),
                           cp_cma_coef_cox = all(iteration$coef$cover_cma_coef_cox))

    # Append to all_coef
    all_coef <- rbind(all_coef, tmp_data)
  }
}

# box plot
table_mise_coef <- all_coef %>%
  pivot_longer(cols = c("mise_coef_norm", "mise_coef_cox", "mise_coef_faft2"),
               names_to = "type",
               values_to = "value") %>%
  mutate(est_model = case_when(str_detect(type, "cox") ~ "LFCM",
                               str_detect(type, "norm") ~ "lognormal lfAFT",
                               str_detect(type, "faft2") ~ "loglogistic lfAFT",
                               .default = "lognormal lfAFT"),
         est_model = factor(est_model, 
                            levels = c("loglogistic lfAFT", "lognormal lfAFT", "LFCM", "FTTM")),
         family = recode(family, "cox.ph" = "CoxPH"),
         log_value = log(value))

plot_mise_coef <- table_mise_coef %>%
  filter(beta_type == "simple") %>%
  ggplot(aes(factor(nS), log_value, fill = est_model)) + 
  geom_boxplot(outliers = FALSE, fatten = 1.3) +
  scale_fill_manual(values = my_colors) +
  facet_grid(family~n, labeller = labeller(n = label_both, family = label_value), scales = "free") +
  labs(x = "Density of grid (p)", y = expression("log MISE of"~beta(s)), fill = "Model"
       ) +
  theme(
    strip.text.y = element_blank(),  
    strip.background.y = element_blank()
  )
  
```

### MISE for Estimated Survival Functions
```{r}
all_surv <- data.frame() 

# Loop through all scenarios and iterations to extract 'coef'
for (scenario in all_results) {
  for (iteration in scenario) {
    # Extract data for the current iteration
    tmp_data <- data.frame(scenario = iteration$info$scenario,
                           iter = iteration$info$iter,
                           family = iteration$info$family,
                           n = iteration$info$n,
                           nS = iteration$info$nS,
                           beta_type = iteration$info$beta_type,
                           b = iteration$info$b,
                           mise_surv_norm = mean(iteration$surv$se_surv_norm),
                           mise_surv_cox = mean(iteration$surv$se_surv_cox),
                           mise_surv_faft = mean(iteration$surv$se_surv_faft),
                           mise_surv_faft2 = mean(iteration$surv$se_surv_faft2))

    # Append to all_coef
    all_surv <- rbind(all_surv, tmp_data)
  }
}

table_mise_surv <- all_surv %>%
  pivot_longer(cols = c("mise_surv_norm", "mise_surv_cox", "mise_surv_faft2"),
               names_to = "type",
               values_to = "value") %>%
  mutate(est_model = case_when(str_detect(type, "cox") ~ "LFCM",
                               str_detect(type, "norm") ~ "lognormal lfAFT",
                               str_detect(type, "faft2") ~ "loglogistic lfAFT",
                               .default = "lognormal lfAFT"),
         est_model = factor(est_model, 
                            levels = c("loglogistic lfAFT", "lognormal lfAFT", "LFCM", "FTTM")),
         family = recode(family, "cox.ph" = "CoxPH"),
         log_value = log(value))

plot_mise_surv <- table_mise_surv %>%
  filter(beta_type == "simple") %>%
  ggplot(aes(factor(nS), log_value, fill = est_model)) + 
  geom_boxplot(outliers = FALSE, fatten = 1.3) +
  scale_fill_manual(values = my_colors) +
  facet_grid(family~n, labeller = labeller(n = label_both, family = label_value), scales = "free") +
  labs(x = "Density of grid (p)", y = "log MISE of survival function", fill = "Model"
       ) +
  theme(
    strip.text.y = element_blank(),  
    strip.background.y = element_blank()
  )

plot_mise <- plot_mise_coef + plot_mise_surv + plot_Brier +
  plot_layout(guides = 'collect', axes = 'collect')

ggsave(file.path(fig_dir, "fig_sim_linear.jpeg"), plot_mise, width = 9, height = 4, dpi = 500)
```

### Average Coverage Probability of Pointwise CIs for Coefficient Function
```{r}
# Calculate the average CP of Pointwise CIs for Coefficient Function
table_cp_coef <- all_coef %>%
  group_by(b, beta_type, family, n, nS) %>%
  summarise(
    cp_coef_norm = round(mean(cp_coef_norm, na.rm = TRUE), 3),
    cp_coef_cox = round(mean(cp_coef_cox, na.rm = TRUE), 3),
    cp_coef_faft = round(mean(cp_coef_faft, na.rm = TRUE), 3),
    cp_coef_faft2 = round(mean(cp_coef_faft2, na.rm = TRUE), 3),
    .groups = "drop"
  ) 

# Create summary table
table_cp_coef_1 <- create_table(table_cp_coef, var = c("cp_coef_norm", "cp_coef_cox", "cp_coef_faft", "cp_coef_faft2"), 
                              beta_type = "simple",
                              title = "Average Coverage Probability of Pointwise CIs for Coefficient Function",
                              subtitle = "Beta type: simple")
table_cp_coef_1
table_cp_coef_2 <- create_table(table_cp_coef, var = c("cp_coef_norm", "cp_coef_cox", "cp_coef_faft", "cp_coef_faft2"), 
                              beta_type = "complex",
                              title = "Average Coverage Probability of Pointwise CIs for Coefficient Function",
                               subtitle = "Beta type: complex")
table_cp_coef_2

# Plots
plot_cp_coef <- table_cp_coef %>%
  pivot_longer(cols = c("cp_coef_norm", "cp_coef_cox", "cp_coef_faft", "cp_coef_faft2"),
               names_to = "type",
               values_to = "value") %>%
  mutate(est_model = case_when(str_detect(type, "cox") ~ "mgcv LFCM",
                               str_detect(type, "fttm") ~ "FTTM",
                               str_detect(type, "norm") ~ "mgcv lfAFT",
                               str_detect(type, "faft2") ~ "loglogistic lfAFT",
                               .default = "lognormal lfAFT"))

plot_cp_coef %>%
  filter(beta_type == "simple") %>%
  ggplot(aes(factor(nS), value, fill = est_model)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_hline(yintercept=0.95, linetype="dashed", color = "red") +
  facet_grid(family~n, labeller = label_both) +
  labs(x = "n", y = "Coverage Probability", title = "Average Pointwise Coverage Probability of Coefficient Function Across 100 Simulations", fill = "Model")
```

### Function to Create Summary Table
```{r}
# Transpose dataset from wide to long
create_table <- function(data, var, beta_type, title, subtitle){
  data1 <- data %>%
  pivot_longer(cols = var,
               names_to = "type",
               values_to = "value") %>%
  mutate(est_model = case_when(str_detect(type, "cox") ~ "LFCM",
                               str_detect(type, "norm") ~ "mgcv lfAFT",
                               str_detect(type, "faft2") ~ "loglogistic lfAFT",
                               .default = "lognormal lfAFT"))

  # Combine 'n' and 'nS' into wider columns
  data2 <- data1 %>%
    filter(beta_type == !!beta_type) %>%
    pivot_wider(names_from = c(n, nS), values_from = value, names_sep = "_nS_")

  gt_table <- data2 %>%
    dplyr::select(-c(beta_type, type)) %>%
    gt(groupname_col = "family") %>%
    tab_spanner(label = "N = 100", columns = starts_with("100_")) %>%
    tab_spanner(label = "N = 200", columns = starts_with("200_")) %>%
    tab_spanner(label = "N = 500", columns = starts_with("500_")) %>%
    cols_label(ends_with("nS_50") ~ "nS = 50",
               ends_with("nS_100") ~ "nS = 100",
               ends_with("nS_500") ~ "nS = 500") %>%
   tab_header(title = title, subtitle = subtitle) %>%
   cols_align(align = "center", columns = everything()) %>%
   fmt_number(columns = where(is.numeric), decimals = 3) %>%
   opt_table_outline() %>%
   opt_row_striping()

  return(gt_table)
}
```

### Plot Estimated Coefficient + CI + True Coefficient
Fitted using the log-normal functional AFT model.
```{r}
sub_coef <- data.frame()

# Loop through all scenarios and iterations to extract 'coef'
for (scenario in all_results) {
  counter <- 0  # Initialize a counter

  for (iteration in scenario) {
    # Break the inner loop if 50 iterations for the current scenario are stored
    if (counter >= 1) {
      break
    }

    # Extract data for the current iteration
    time <- seq(0, 1, length.out = iteration$info$nS)
    tmp_data <- data.frame(scenario = iteration$info$scenario,
                           iter = iteration$info$iter,
                           family = iteration$info$family,
                           n = iteration$info$n,
                           nS = iteration$info$nS,
                           b = iteration$info$b,
                           censor_rate = iteration$info$censor_rate,
                           time = time,
                           beta_type = iteration$info$beta_type,
                           true_coef = iteration$coef$true_coef,
                           est_coef_norm = iteration$coef$est_coef_norm,
                           lb_coef_norm = iteration$coef$lb_coef_norm,
                           ub_coef_norm = iteration$coef$ub_coef_norm,
                           est_coef_faft = iteration$coef$est_coef_faft,
                           lb_coef_faft = iteration$coef$lb_coef_faft,
                           ub_coef_faft = iteration$coef$ub_coef_faft,
                           est_coef_faft2 = iteration$coef$est_coef_faft2,
                           lb_coef_faft2 = iteration$coef$lb_coef_faft2,
                           ub_coef_faft2 = iteration$coef$ub_coef_faft2,
                           cma_lb_coef_norm = iteration$coef$cma_lb_coef_norm,
                           cma_ub_coef_norm = iteration$coef$cma_ub_coef_norm,
                           est_coef_cox = iteration$coef$est_coef_cox,
                           lb_coef_cox = iteration$coef$lb_coef_cox,
                           ub_coef_cox = iteration$coef$ub_coef_cox,
                           cma_lb_coef_cox = iteration$coef$cma_lb_coef_cox,
                           cma_ub_coef_cox = iteration$coef$cma_ub_coef_cox)

    # Append to all_coef
    sub_coef <- rbind(sub_coef, tmp_data)

    # Increment the counter
    counter <- counter + 1
  }
}

# Ensure the required directory for saving plots exists
output_dir <- "../Figures"
if (!dir.exists(output_dir)) {
  dir.create(output_dir)
}

# select a subset of scenarios
sub_coef_2 <- sub_coef %>%
  filter(family == "loglogistic" & beta_type == "simple" & nS == 500)

# Loop through each unique scenario
scenarios <- unique(sub_coef_2[, c("family", "n", "nS", "beta_type", "b", "censor_rate")])
for (i in 1:nrow(scenarios)) {
  # Extract the scenario information
  scenario <- scenarios[i, ]
  family <- scenario$family
  n <- scenario$n
  nS <- scenario$nS
  beta_type <- scenario$beta_type
  b <- scenario$b
  censor_rate <- scenario$censor_rate

# Filter data for the current scenario
  scenario_data <- sub_coef_2 %>%
    filter(family == !!family, n == !!n, nS == !!nS, beta_type == !!beta_type, b == !!b)

# Create the plot
p <- ggplot(data = scenario_data, aes(x = time)) +
  # geom_ribbon(aes(ymin = lb_coef_faft, ymax = ub_coef_faft, fill = "Pointwise CI"), alpha = 0.5) +
  # geom_line(aes(y = est_coef_faft, color = "Estimated Coefficient"), size = 1) +
  geom_ribbon(aes(ymin = lb_coef_faft2, ymax = ub_coef_faft2, fill = "Pointwise CI"), alpha = 0.5) +
  geom_line(aes(y = est_coef_faft2, color = "Estimated Coefficient"), size = 1) +
  # geom_ribbon(aes(ymin = lb_coef_norm, ymax = ub_coef_norm, fill = "Pointwise CI"), alpha = 0.5) +
  # geom_line(aes(y = est_coef_norm, color = "Estimated Coefficient"), size = 1) +
  # geom_ribbon(aes(ymin = lb_coef_cox, ymax = ub_coef_cox, fill = "Pointwise CI"), alpha = 0.5) +
  # geom_line(aes(y = est_coef_cox, color = "Estimated Coefficient"), size = 1) +
  geom_line(aes(y = true_coef, color = "True Coefficient"), linetype = "dashed", size = 1) +
  scale_color_manual(values = c("Estimated Coefficient" = "blue", "True Coefficient" = "red")) +
  scale_fill_manual(values = c(
    "Pointwise CI" = "lightblue"
  )) +
  labs(
    x = "Time",
    y = "Coefficient",
    title = paste("family =",family, "n =", n, "nS =", nS, "beta_type =", beta_type),
    subtitle = paste("b=", b, "censor rate =", censor_rate),
    color = NULL,
    fill = NULL
  ) +
  theme_minimal()
print(p)
}

# Save the plot
# file_name <- paste0(output_dir, "/", family, "_", n, "_", nS, "_", beta_type, ".png")
# ggsave(file_name, plot = p, width = 8, height = 6)
```

```{r, include=FALSE}
### First 20 coeffcient estimations vs. true coefficient
# sub_coef <- data.frame() 
# 
# # Loop through all scenarios and iterations to extract 'coef'
# for (scenario in all_results) {
#   counter <- 0  # Initialize a counter
#   
#   for (iteration in scenario) {
#     # Break the inner loop if 50 iterations for the current scenario are stored
#     if (counter >= 20) {
#       break
#     }
#     
#     # Extract data for the current iteration
#     time <- seq(0, 1, length.out = iteration$info$nS)
#     tmp_data <- data.frame(scenario = iteration$info$scenario,
#                            iter = iteration$info$iter,
#                            family = iteration$info$family,
#                            n = iteration$info$n,
#                            nS = iteration$info$nS,
#                            k = iteration$info$k,
#                            time = time,
#                            # beta_type = iteration$info$beta_type,
#                            true_coef = iteration$coef$true_coef,
#                            est_coef_norm = iteration$coef$est_coef_norm,
#                            est_coef_cox = iteration$coef$est_coef_cox,
#                            se_coef_norm = iteration$coef$se_coef_norm,
#                            se_coef_cox = iteration$coef$se_coef_cox,
#                            se_coef_sieve = iteration$coef$se_coef_sieve,
#                            cp_coef_norm = iteration$coef$cp_coef_norm,
#                            cp_coef_cox = iteration$coef$cp_coef_cox,
#                            cp_cma_coef_norm = iteration$coef$cp_cma_coef_norm,
#                            cp_cma_coef_cox = iteration$coef$cp_cma_coef_cox)
# 
#     # Append to all_coef
#     sub_coef <- rbind(sub_coef, tmp_data)
#     
#     # Increment the counter
#     counter <- counter + 1
#   }
# }
# 
# # Ensure the required directory for saving plots exists
# output_dir <- "../Figures"
# if (!dir.exists(output_dir)) {
#   dir.create(output_dir)
# }
# 
# # Loop through each unique scenario
# scenarios <- unique(sub_coef[, c("family", "n", "nS", "k")])
# for (i in 1:nrow(scenarios)) {
#   # Extract the scenario information
#   scenario <- scenarios[i, ]
#   family <- scenario$family
#   n <- scenario$n
#   nS <- scenario$nS
#   k <- scenario$k
#   
#   # Filter data for the current scenario
#   scenario_data <- sub_coef %>%
#     filter(family == !!family, n == !!n, nS == !!nS, k == !!k)
#   
#   scenario_data_long <- scenario_data %>%
#     select(iter, family, n, nS, k, time, true_coef, est_coef_norm, est_coef_cox) %>%
#     pivot_longer(cols = c(true_coef, est_coef_norm, est_coef_cox),
#                  names_to = "coef_type",
#                  values_to = "coef_value")
#   
#   # Create the plot
#   p <- ggplot(data = scenario_data_long, aes(x = time, y = coef_value, color = coef_type, group = interaction(iter, coef_type))) +
#     geom_line(size = 0.5) +
#     #scale_color_manual(
#     #  values = c("true_coef" = "red", "est_coef_norm" = "green", "est_coef_cox" = "blue"),
#     #  labels = c("True Coef", "Estimated Coef (Norm)", "Estimated Coef (Cox)")
#     #) +
#     labs(title = paste("family =",family, "n =", n, "nS =", nS, "k =", k),
#          x = "Time", y = "Coefficient",
#          color = "Type") +
#     theme_minimal()
#   
#   # Save the plot
#   file_name <- paste0(output_dir, "/", family, "_", n, "_", nS, "_", k, ".png")
#   ggsave(file_name, plot = p, width = 8, height = 6)
# }
```